[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Digital Earth Pacific"
authors = [{name = "Sachindra Singh", email = "sachindras@spc.int"}]
dynamic = ["version", "description"]
